FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py ./app.py
COPY templates ./templates
COPY static ./static

ENV PORT=80
EXPOSE 80

CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:80", "app:app"]